###
GET http://localhost:8080/clients?name=name12345&surname=sur123qwe&email=mail123@mail.mail848441&phone=66666

###
GET http://localhost:8080/clients/2

###
POST http://localhost:8080/clients
Content-Type: application/json

{
  "name": "name123",
  "surname": "surname123",
  "email": "mail123@mail.mail848440",
  "phone": "984984984"
}

###
PUT http://localhost:8080/clients
Content-Type: application/json

{
  "id": 2,
  "name": "name12345",
  "surname": "surname123",
  "email": "mail123@mail.mail848441",
  "phone": "984984984"
}

###
DELETE http://localhost:8080/clients/2


