### поиск по имени, фамилии, email, роли, сортировка, пагинация
GET http://localhost:8080/employees?name=name123&surname=surname123&email=mail123@mail.mail111&role=ADMINISTRATOR

### поиск по id
GET http://localhost:8080/employees/40

### добавление
POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "name123",
  "surname": "surname123",
  "email": "mail123@mail.mail848440",
  "password": "password123",
  "role": "администратор"
}

### обновление
PUT http://localhost:8080/employees
Content-Type: application/json

{
  "id": 58,
  "name": "name123123",
  "surname": "surname123",
  "email": "mail123@mail.mailhjhр",
  "password": "password123123",
  "role": "администратор"
}

### удаление по id
DELETE http://localhost:8080/employees/58
