### поиск по имени, фамилии, email, роли, сортировка, пагинация
GET http://localhost:8080/employees/search?name=name123&surname=surname123&email=mail123@mail.mail111&role=ADMINISTRATOR

### поиск по id
GET http://localhost:8080/employees/53

### добавление
POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "name123",
  "surname": "surname123",
  "email": "mail123@mail.mail88",
  "password": "password123",
  "role": "MANAGER"
}

### обновление
PUT http://localhost:8080/employees
Content-Type: application/json

{
  "id": 53,
  "name": "name123123",
  "surname": "surname123",
  "email": "mail123@mail.mailhjh",
  "password": "password123123",
  "role": "MANAGER"
}

### удаление по id
DELETE http://localhost:8080/employees/53
