spring:
  application:
    name: crm
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5433/crm
    username: postgres
    password: 54Ykr7UUVXk2RLh
    driverClassName: org.postgresql.Driver
